name: Build multi-platform

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - build: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - build: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin

          - build: windows-gnu
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu

          - build: windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag
        shell: bash
        run: |
          case "$GITHUB_REF_TYPE" in
            branch)
              echo "VERSION=$(echo "$GITHUB_REF" | tr '/' '-')" >> $GITHUB_ENV
              ;;
            tag)
              echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
              ;;
            *)
              echo "VERSION=unknown" >> $GITHUB_ENV
          esac

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Build Archive
        shell: bash
        run: |
          env | sort
          BIN="rusm64"
          DIR="$BIN-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$DIR"

          find "target/${{ matrix.target }}/release" -type f -perm -u+x -exec cp \{\} "$DIR" \;

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$DIR.zip" "$DIR"
            echo "ASSET=$DIR.zip" >> $GITHUB_ENV
          else
            tar -czf "$DIR.tar.gz" "$DIR"
            echo "ASSET=$DIR.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}

